Changed out dockerhub log in process

diff --git a/.github/workflows/publish_develop_image.yml b/.github/workflows/publish_develop_image.yml
--- a/.github/workflows/publish_develop_image.yml
+++ b/.github/workflows/publish_develop_image.yml
@@ -41,11 +41,24 @@ jobs:
     # official Volttron Dockerhub page at https://hub.docker.com/repository/docker/eclipsevolttron/volttron/general
     # On instructions how to do this, see https://docs.github.com/en/actions/guides/publishing-docker-images
     # https://github.com/docker/login-action
+#     - name: Login to DockerHub
+#       uses: docker/login-action@v3
+#       with:
+#         username: ${{ vars.DOCKER_USER }}
+#         password: ${{ secrets.DOCKER_API_TOKEN }}
     - name: Login to DockerHub
-      uses: docker/login-action@v3
-      with:
-        username: ${{ vars.DOCKER_USER }}
-        password: ${{ secrets.DOCKER_API_TOKEN }}
+      run: |
+        if [ -n "${{ vars.DOCKER_USER }}" -a -n "${{ secrets.DOCKER_API_TOKEN }}" ]; then
+          echo " "
+          echo "Connecting to docker"
+        
+          echo "${{ secrets.DOCKER_API_TOKEN }}" | docker login -u "${{ vars.DOCKER_USER }}" --password-stdin
+          status=$?
+          if [ $status -ne 0 ]; then
+            echo "Error: status $status"
+            exit 1
+          fi
+        fi
 
     - name: Build and push
       id: docker_build
