testing pull_request_target

diff --git a/.github/workflows/publish_develop_image.yml b/.github/workflows/publish_develop_image.yml
--- a/.github/workflows/publish_develop_image.yml
+++ b/.github/workflows/publish_develop_image.yml
@@ -7,7 +7,7 @@ on:
     branches:
       - develop
   workflow_dispatch:
-  pull_request:
+  pull_request_target:
     types: [opened, reopened, synchronize]
 env:
   # Image name on Volttron DockerHub account at https://hub.docker.com/orgs/eclipsevolttron
@@ -51,50 +51,64 @@ jobs:
           fi
         fi
 
-    - name: Build Image
+    - name: Build and push
       id: docker_build
-      run: |
-        echo "Building image"
-        echo "docker buildx build \
-          --build-arg volttron_git_branch=${{ env.VOLTTRON_GIT_BRANCH }} \
-          --build-arg volttron_repo=${{ env.VOLTTRON_GIT_REPO }} \
-          --platform linux/amd64,linux/arm64 \
-          -t ${{ env.IMAGE_BASE_NAME }}:${{ env.IMAGE_TAG }} \
-          -f ${{ env.DOCKERFILE || './Dockerfile' }} --no-cache --force-rm --load ."
-        docker buildx build \
-          --build-arg volttron_git_branch=${{ env.VOLTTRON_GIT_BRANCH }} \
-          --build-arg volttron_repo=${{ env.VOLTTRON_GIT_REPO }} \
-          --platform linux/amd64,linux/arm64 \
-          -t ${{ env.IMAGE_BASE_NAME }}:${{ env.IMAGE_TAG }} \
-          -f ${{ env.DOCKERFILE || './Dockerfile' }} --load .
-        status=$?
-        if [ $status -ne 0 ]; then
-          echo "Error: status $status"
-          exit 1
-        fi
+      uses: docker/build-push-action@v2
+      with:
+        context: .
+        file: ${{ env.DOCKERFILE || './Dockerfile' }}
+        platforms: linux/amd64,linux/arm64
+        build-args: |
+          volttron_git_branch=${{ env.VOLTTRON_GIT_BRANCH }}
+          volttron_repo=${{ env.VOLTTRON_GIT_REPO }}
+        push: true
+        tags: |
+          ${{ env.IMAGE_BASE_NAME }}:${{ env.IMAGE_TAG }}
 
-    - name: Push Image
-      id: docker_push
-      run: |
-        echo "Pushing image"
-        # docker images
-        echo "docker push ${{ env.IMAGE_BASE_NAME }}:${{ env.IMAGE_TAG }}"
-        echo "digest=$(docker push ${{ env.IMAGE_BASE_NAME }}:${{ env.IMAGE_TAG }} | grep '${{env.IMAGE_TAG}}: digest:')" >> $GITHUB_OUTPUT
-        status=$?
-        if [ $status -ne 0 ]; then
-          echo "Error: status $status"
-          exit 1
-        fi
+#     - name: Build Image
+#       id: docker_build
+#       run: |
+#         echo "Building image"
+#         echo "docker buildx build \
+#           --build-arg volttron_git_branch=${{ env.VOLTTRON_GIT_BRANCH }} \
+#           --build-arg volttron_repo=${{ env.VOLTTRON_GIT_REPO }} \
+#           --platform linux/amd64,linux/arm64 \
+#           -t ${{ env.IMAGE_BASE_NAME }}:${{ env.IMAGE_TAG }} \
+#           -f ${{ env.DOCKERFILE || './Dockerfile' }} --no-cache --force-rm --load ."
+#         docker buildx build \
+#           --build-arg volttron_git_branch=${{ env.VOLTTRON_GIT_BRANCH }} \
+#           --build-arg volttron_repo=${{ env.VOLTTRON_GIT_REPO }} \
+#           --platform linux/amd64,linux/arm64 \
+#           -t ${{ env.IMAGE_BASE_NAME }}:${{ env.IMAGE_TAG }} \
+#           -f ${{ env.DOCKERFILE || './Dockerfile' }} --load .
+#         status=$?
+#         if [ $status -ne 0 ]; then
+#           echo "Error: status $status"
+#           exit 1
+#         fi
+#
+#     - name: Push Image
+#       id: docker_push
+#       run: |
+#         echo "Pushing image"
+#         # docker images
+#         echo "docker push ${{ env.IMAGE_BASE_NAME }}:${{ env.IMAGE_TAG }}"
+#         echo "digest=$(docker push ${{ env.IMAGE_BASE_NAME }}:${{ env.IMAGE_TAG }} | grep '${{env.IMAGE_TAG}}: digest:')" >> $GITHUB_OUTPUT
+#         status=$?
+#         if [ $status -ne 0 ]; then
+#           echo "Error: status $status"
+#           exit 1
+#         fi
 
-    - name: Show publish digest
-      run: |
-        echo "docker_push.outputs.digest: ${{ steps.docker_push.outputs.digest }}"
+#    - name: Show publish digest
+#      run: |
+#        echo "docker_push.outputs.digest: ${{ steps.docker_push.outputs.digest }}"
 
     - name: Check image publish
-      if: steps.docker_push.outputs.digest == ''
+      if: steps.docker_build.outputs.digest == ''
       run: exit 1
 
     - name: Image Digest
-      run: echo ${{ steps.docker_push.outputs.digest }}
+      run: echo ${{ steps.docker_build.outputs.digest }}
 
     - run: echo "🍏 This job's status is ${{ job.status }}."
